name: Build jobs
# Triggered by changes in code-specific or job-specific files

on:
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/*.yml'
      - 'pyproject.toml'
      - 'tox.ini'
      - '!docs/**'
  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Generic pre-commit checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - run: pip install pre-commit
      - run: SKIP=mypy pre-commit run --all-files

  mypy:
    name: Mypy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - run: pip install pre-commit
      - run: pre-commit run mypy --all-files

  tests:
    name: Test ${{ matrix.tox_job }} on ${{ matrix.os_version }}
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        include:
          - tox_job: pypy3-no_pycurl
            python: "pypy3.11"
            os_version: "ubuntu-24.04"
          - tox_job: py310
            python: "3.10"
            os_version: "ubuntu-24.04"
          - tox_job: py311
            python: "3.11"
            os_version: "ubuntu-24.04"
          - tox_job: py312
            python: "3.12"
            os_version: "ubuntu-24.04"
          - tox_job: py313
            python: "3.13"
            os_version: "ubuntu-24.04"
          - tox_job: py314
            python: "3.14"
            os_version: "ubuntu-24.04"

          - tox_job: pypy3-no_pycurl
            python: "pypy3.11"
            os_version: "windows-2022"
          - tox_job: py310
            python: "3.10"
            os_version: "windows-2022"
          - tox_job: py311
            python: "3.11"
            os_version: "windows-2022"
          - tox_job: py312
            python: "3.12"
            os_version: "windows-2022"
          - tox_job: py313
            python: "3.13"
            os_version: "windows-2022"
          - tox_job: py314
            python: "3.14"
            os_version: "windows-2022"

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - run: pip install tox coverage

      - name: Install system deps on Linux
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev

      - name: Run ${{ matrix.tox_job }} tox job
        run: tox -e ${{ matrix.tox_job }}

      - run: coverage combine
      - run: coverage report
      - run: coverage xml -i

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          file: ./coverage.xml
